title: "Deploy on Friday!"
author: "Lars Rosenquist"
description: "Helping developers build better software better" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

show_excerpts: true
bluesky_username: "larsrosenquist.bsky.social"
github_username: "nlxarosa"
linkedin_username: "larsrosenquist"
mastodon:
- username: "larsrosenquist"
  instance: "mastodon.social" 

theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
